### ISSUE TITLE
xapian_sortable_serialise() wrapping flawed

### ISSUE THREAD

**Issue by ojwb** [endlessm/xapian-glib#54]
The `std::string` returned by `Xapian::sortable_serialise()` is essentially a binary blob, and may contain embedded zero bytes.  But the current wrappers document the serialised form as `(array zero-terminated=1)` and handle the data assuming the first zero byte marks the end of the string.

Because of how the serialisation inherently works, this generally results in rounding-off type errors, rather than completely the wrong answer being returned.  For example, if you roundtrip `2049.0` through the serialisation as wrapped by xapian-glib, you get `2048.0` back out.

However for numbers which produce a serialisation starting with a zero byte, the truncation means you'll get -infinity back.  Not sure exactly which values trigger this, but they must be negative.

To fix this, I think the length needs to be returned and passed back in, something like:

```
char *
xapian_sortable_serialise (double value, size_t *len)
{
  char *buf;
  const string &result = Xapian::sortable_serialise (value);
  *len = result.size();
  buf = g_malloc (*len);
  memcpy (buf, result.data (), *len);
  return buf;
}

double
xapian_sortable_unserialise (const char *value, size_t len)
{
  return Xapian::sortable_unserialise (string (value, len));
}
```

But that's clearly an incompatible change, so I'm not sure how best to address this.

I noticed looking at the git history that `xapian_document_add_numeric_value ()` was added because these wrappers aren't usable from Gjs (because they don't return UTF-8 strings), so perhaps they aren't actually used by anyone currently (which would explain why nobody's noticed this issue - I spotted it while looking at the code).

**Comment by ebassi** [comment]
On a purely technical standpoint, xapian-glib follows the same pattern as other libraries in the G* platform: API is only added during odd-numbered development cycles, and once it's part of an even-numbered stable cycle it cannot be touched any more, only deprecated.

The 1.3 cycle for xapian-glib is the unstable cycle leading to the stable 1.4 one; this means we can change API added during this cycle with no backward compatibility concerns.

Nevertheless, we use unstable releases of xapian-glib in our SDK, so we need to be careful when changing the API.

I'd like to release xapian-glib 1.4 with the version 1 of the `com.endlessm.apps.Sdk` runtime, so if we want to change the API, we need to be doing this now. @ptomato, @cosimoc — what do you think?

@ojwb — adding a length argument is absolutely fine; to fit into the expected API patterns, I'd either use:

```cpp
guint8 *
xapian_sortable_serialise (double value, gsize *len);

double
xapian_sortable_unserialise (const guint8 *data, gsize len);
```

As that would make it clear we're using a byte array. Alternatively, use `guchar*`, since it's what other GLib API does when it comes to binary blobs with embedded `NUL` bytes. All introspection-based language bindings will be able to handle either case.

**Comment by cosimoc** [comment]
@ebassi Sounds like a good idea, and I would agree with doing this right now if we can, before the SDK1 release.

**Comment by ebassi** [comment]
As a fallback plan, I can remove the current sortable_serialise/unserialise bindings, spin 1.4.0, and then we can add the proper API later.

**Comment by ojwb** [comment]
OK, I'll get this done today.

Sounds like `guchar*` is probably preferable for consistency, so I'll go with that unless someone shouts.
